### ISSUE TITLE
Add user-made tools

### ISSUE THREAD

**Issue by daviddavo** [omnivore-app/docs.omnivore#120]
Hello, I made a tool to import from Pocket and upload it to Omnivore. I was thinking on adding it to https://docs.omnivore.app/using/importing.html, but I don't know if its OK to put usermade tools as there are only official applications.

In case of adding it, how should I approach it?

**Comment by jacksonh** [comment]
hey yeah this is an awesome idea thanks!  Sorry it took so long for me to see this issue, i guess i dont' have notifications setup correctly for this repo. I am thinking we could make it a page that is part of the `Using` section, so it doesn't get lost in development.

**Comment by daviddavo** [comment]
In my case, is more like a tool (you need to install deps, run a jupyter notebook, etc.) than a third party application. Personally, I'd add each tool to its respective section too (like Importing Data)

**Comment by matthieugd** [comment]
Maybe @daviddavo you can create a public repo with your tool and we can link it from the Import doc page ?

**Comment by matthieugd** [comment]
My mistake I didn’t see that the integration was now official. I made a PR to add a mention in the docs.

**Comment by daviddavo** [comment]
I didn't know it was now official too. I checked a couple of weeks ago so it must be recent, thank you for noticing!
