### ISSUE TITLE
Add section about Pocket import/integration to importing.md

### ISSUE THREAD

**Issue by daytonb** [omnivore-app/docs.omnivore#136]
I am playing with migrating from Pocket to omnivore. I found an [article](https://blog.ddavo.me/posts/tutorials/pocket-to-omnivore/) where the author wrote a jupyter notebook to take the HTML export from Pocket, process it with Python, and upload it via API access to omnivore. I also found a [reddit post](https://www.reddit.com/r/logseq/comments/zvzldg/pocket_export_to_omnivore/) that mentioned that an official means was implemented. I didn't find any mention of this on the https://docs.omnivore.app/using/importing.html, but later stumbled onto it in https://omnivore.app/settings/integrations. Now that the integration is there, the importing.md should have  a short section about the Pocket integration/import.

**Comment by matthieugd** [comment]
We can close this issue ?
