### ISSUE TITLE
.opml import functionality for Feeds

### ISSUE THREAD

**Issue by Jonathunky** [omnivore-app/docs.omnivore#156]
Hello!

Usually, services like Feedly, NewsBlur, and standalone RSS readers allow to export current list of subscriptions in a standard OPML file, which then can be imported into other similar services and apps.

It would be nice if Feeds section in Omnivore could support this feature.

Thanks ever so much.

**Comment by matthieugd** [comment]
Hello @Jonathunky, If i understand correctly your message this is a feature request ?

I will encourage you to post it either on the discord channel dedicated to them [here](https://discord.com/channels/844965259462311966/1158760888229179473) or on the main repo [here](https://github.com/omnivore-app/omnivore/issues) and close this issue.
