### ISSUE TITLE
filename variables obsidian

### ISSUE THREAD

**Issue by berot3** [omnivore-app/docs.omnivore#158]
https://github.com/omnivore-app/docs.omnivore/blob/f0f8b85c9c3f6e4816886627811a6e85143e5e61/docs/integrations/obsidian.md?plain=1#L62

Variables available **for filename**

afaik this is the title, date and now, ID.

_Originally posted by @berot3 in https://github.com/omnivore-app/obsidian-omnivore/issues/154#issuecomment-1812226028_

**Comment by jacksonh** [comment]
Thanks I think this one is done
