### ISSUE TITLE
Note on page level is missing in tempate example

### ISSUE THREAD

**Issue by limex** [omnivore-app/docs.omnivore#167]
First: Great work on the app an the obsidian integration.

My 2 pence: I think https://github.com/omnivore-app/docs.omnivore/blob/main/docs/integrations/obsidian.md is missing the note on page level.
There should be a {{{note}}} outside the highlights loop as well. People might miss that. 
You might also want to adapt the default Article Template in the Settings Dialog of the Plugin.

BR Gü

**Comment by jacksonh** [comment]
This is there now. Thanks!
