### ISSUE TITLE
Add export functionality

### ISSUE THREAD

**Issue by boretom** [omnivore-app/docs.omnivore#174]
Hi,

I'm a new to Omnivore. Up to now I use/d Pocket and/or wallabag and like the UI and responsiveness of Omnivore.

I did search the issue list here and the documentation and I do miss the possibility to export all items, including labels, notes and so on.

Is such a feature planned?

**Comment by jacksonh** [comment]
Hi @boretom what most people do is sync their data to something like Logseq or Obsidian. We also have an open API so you can query it and save everything in any format you want. 

As per an export tool, I'd like to make some, but an exporter is really only as good as the subsequent importer for another tool

**Comment by boretom** [comment]
> As per an export tool, I'd like to make some, but an exporter is really only as good as the subsequent importer for another tool

But having an export I can then at least create an import script for another service. Right now I'd have to create a script or app to use the API. To me that is more complicated than a let's say a JSON converter to <whatever the other service wants>.
