### ISSUE TITLE
Add links to edit documentation

### ISSUE THREAD

**Issue by dpschen** [omnivore-app/docs.omnivore#6]
There is a lot of friction in improving the docs for users (aka a Google search away). This could be improved by adding a link to the respective markdown file on GitHub.

**Comment by jacksonh** [comment]
Awesome thanks, I think this is a vitepress feature so I'll try to figure out how to enable it.

**Comment by jacksonh** [comment]
Done!

**Comment by dpschen** [comment]
🥳
